### PR TITLE
merge the existing patches from upstream

### PR DESCRIPTION
**Pull request by CvH**
as upstream is dead >1year I pr the changes here

compiles fine with 2.3.8

### CODE REVIEW

**Comment by CvH** [comment]
ping @glenvt18 ^^^^

**Comment by glenvt18** [comment]
@CvH 
> as upstream is dead >1year ...

Looks so.

I currently use these commits with 2.3.8. Works fine. 'Make compatible with VDR 2.3.4' commit is only needed if you build against 2.3.4. It fixes an issue introduced in 2.3.4 which was then fixed in 2.3.5. Though keeping this commit is harmless (and provides compatibility across all VDR versions).

BTW. Is it now a new upstream repository?

**Comment by CvH** [comment]
@glenvt18 I have no idea as github (and releasing at a cvs in general) hasn't got a much love from the vdr community - so lets try, optional you can email the dev and wait for another year ;)

**Comment by belaid38** [comment]
@glenvt18   @CvH   I hope you want the latest version vdr 2.3.8  for libreelec   i have wetek play 2

**Comment by CvH** [comment]
@belaid38 https://github.com/LibreELEC/LibreELEC.tv/pull/2332 <- patch ^^^^ is there too

**Comment by CvH** [comment]
was merged years ago

**Pull request closed without merging**
